[audio, sampleRate] = audioread("car1.wav");
%specgram(audio, 256, sampleRate);
n = length(audio);
filter = fir1(100, [0.07, 0.13], 'pass');
%filter = fir1(100, 0.07, 'high');
%filter = fir1(100, 0.13, 'low');
audio = conv(audio, filter, 'valid');
audio = audio.*2;
%audio = (audio.^1.2)./max(audio);
audiowrite('car2.wav', audio, sampleRate);
specgram(audio, 256, sampleRate);